In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
data = pd.read_excel('./data/NYCRideData_2022.xlsx',
                    parse_dates=['Date'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 578 entries, 0 to 577
Data columns (total 15 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Date                                    578 non-null    datetime64[ns]
 1   Month/Year                              578 non-null    object
 2   License Class                           578 non-null    object
 3   Trips Per Day                           578 non-null    int64
 4   Farebox Per Day                         574 non-null    object
 5   Unique Drivers                          578 non-null    int64
 6   Unique Vehicles                         578 non-null    int64
 7   Vehicles Per Day                        578 non-null    int64
 8   Avg Days Vehicles on Road               578 non-null    float64
 9   Avg Hours Per Day Per Vehicle           578 non-null    float64
 10  Avg Days Drivers on Road                578 non-null    float64
 11  Avg Hours Per Day Per Driver            578 non-null    float64
 12  Avg Minutes Per Trip                    578 non-null    object
 13  Percent of Trips Paid with Credit Card  578 non-null    object
 14  Trips Per Day Shared                    576 non-null    object
dtypes: datetime64[ns](1), float64(4), int64(4), object(6)
memory usage: 67.9+ KB

In [3]:
data['year'] = pd.DatetimeIndex(data.Date).year
data['month'] = pd.DatetimeIndex(data.Date).month
data

,Date,Month/Year,License Class,Trips Per Day,Farebox Per Day,Unique Drivers,Unique Vehicles,Vehicles Per Day,Avg Days Vehicles on Road,Avg Hours Per Day Per Vehicle,Avg Days Drivers on Road,Avg Hours Per Day Per Driver,Avg Minutes Per Trip,Percent of Trips Paid with Credit Card,Trips Per Day Shared,year,month
0,2010-01-01,2010-01,Yellow,479376,4968817,30659,13305,12727,29.7,14.3,22.5,8.2,-,0.32,-,2010,1
1,2010-02-01,2010-02,Yellow,397969,3392416,28255,12171,10045,23.1,14.6,17.6,8.3,11.1,0.35,-,2010,2
2,2010-03-01,2010-03,Yellow,415567,3011750,28709,12183,10382,26.4,15.1,20.4,8.3,11.5,0.35,-,2010,3
3,2010-04-01,2010-04,Yellow,504798,5502545,30827,13326,12856,28.9,14.8,22.3,8.3,-,0.35,-,2010,4
4,2010-05-01,2010-05,Yellow,499374,5561218,30950,13309,12729,29.6,14.8,22.7,8.3,-,0.35,-,2010,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,2021-11-01,2021-11,Green,3607,82076,1312,1270,741,17.5,3.9,17.2,3.8,20.6,0.73,0,2021,11
574,2021-11-01,2021-11,FHV - High Volume,534718,-,69410,67433,44979,20.0,6.5,19.7,6.4,19,-,0,2021,11
575,2021-12-01,2021-12,Yellow,103585,1903870,9552,6908,5657,25.4,9.0,21.5,7.7,15.2,0.77,0,2021,12
576,2021-12-01,2021-12,FHV - High Volume,517884,-,70302,68257,44289,20.1,6.4,19.8,6.3,18,-,0,2021,12
577,2021-12-01,2021-12,Green,3223,70840,1299,1232,705,17.8,3.6,17.1,3.6,19.5,0.69,0,2021,12

In [4]:
yellow = data[data['License Class'] == 'Yellow']
yellow

,Date,Month/Year,License Class,Trips Per Day,Farebox Per Day,Unique Drivers,Unique Vehicles,Vehicles Per Day,Avg Days Vehicles on Road,Avg Hours Per Day Per Vehicle,Avg Days Drivers on Road,Avg Hours Per Day Per Driver,Avg Minutes Per Trip,Percent of Trips Paid with Credit Card,Trips Per Day Shared,year,month
0,2010-01-01,2010-01,Yellow,479376,4968817,30659,13305,12727,29.7,14.3,22.5,8.2,-,0.32,-,2010,1
1,2010-02-01,2010-02,Yellow,397969,3392416,28255,12171,10045,23.1,14.6,17.6,8.3,11.1,0.35,-,2010,2
2,2010-03-01,2010-03,Yellow,415567,3011750,28709,12183,10382,26.4,15.1,20.4,8.3,11.5,0.35,-,2010,3
3,2010-04-01,2010-04,Yellow,504798,5502545,30827,13326,12856,28.9,14.8,22.3,8.3,-,0.35,-,2010,4
4,2010-05-01,2010-05,Yellow,499374,5561218,30950,13309,12729,29.6,14.8,22.7,8.3,-,0.35,-,2010,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,2021-08-01,2021-08,Yellow,89901,1611851,7471,5888,4700,24.7,8.8,21.1,8.2,13.9,0.77,-,2021,8
562,2021-09-01,2021-09,Yellow,98724,1826391,8502,6218,5069,24.5,9.0,19.9,8.1,15.2,0.78,-,2021,9
567,2021-10-01,2021-10,Yellow,111638,1993228,9154,6600,5555,26.1,9.5,21.7,8.2,15.1,0.79,-,2021,10
572,2021-11-01,2021-11,Yellow,115660,2103014,9516,6810,5763,25.4,9.5,21.3,8.2,15.4,0.79,0,2021,11
575,2021-12-01,2021-12,Yellow,103585,1903870,9552,6908,5657,25.4,9.0,21.5,7.7,15.2,0.77,0,2021,12

In [5]:
year_and_month = yellow.pivot(index='year', columns='month', values='Trips Per Day')
year_and_month

month,1,2,3,4,5,6,7,8,9,10,11,12
year,,,,,,,,,,,,
2010,479376,397969,415567,504798,499374,494137,472752,404115,517972,457996,463701,445727
2011,434297,507167,518212,490577,501708,503152,475475,427740,487470,506532,484122,481410
2012,482811,516585,520764,515848,502097,503139,463784,463841,484783,468377,459114,474005
2013,476544,499556,507914,503249,492962,479148,445861,406246,470147,483921,479527,450634
2014,444537,466522,497661,487275,476569,460393,422771,409305,445782,459087,440576,419776
...,...,...,...,...,...,...,...,...,...,...,...,...
2017,313229,327451,332075,334865,325857,321877,277042,271676,298163,315084,309471,306706
2018,282565,303280,304169,310169,297508,290362,253186,253182,267983,284121,271501,263609
2019,247315,250654,252634,247742,244017,231335,202443,194798,217747,231171,227654,220786
2020,206604,217216,96993,7928,11237,18325,25816,32491,44646,54221,50285,47145
2021,44052,48499,61643,71982,80499,94130,91011,89901,98724,111638,115660,103585

In [6]:
yellow.describe()

,Trips Per Day,Unique Drivers,Unique Vehicles,Vehicles Per Day,Avg Days Vehicles on Road,Avg Hours Per Day Per Vehicle,Avg Days Drivers on Road,Avg Hours Per Day Per Driver,year,month
count,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000
mean,341467.784722,25391.750000,11762.319444,10866.208333,27.450000,12.640972,21.296528,7.897917,2015.500000,6.500000
std,147786.067946,8819.050142,2923.212682,3184.173092,3.139039,2.413146,1.617449,0.450558,3.464102,3.464102
min,7928.000000,2208.000000,2191.000000,982.000000,13.500000,5.300000,13.200000,5.100000,2010.000000,1.000000
25%,253045.000000,22260.500000,11931.500000,10669.250000,27.000000,11.300000,21.075000,7.800000,2012.750000,3.750000
50%,375616.000000,29365.500000,13200.500000,12236.500000,28.500000,13.300000,21.700000,8.000000,2015.500000,6.500000
75%,468819.500000,31279.500000,13338.250000,12835.500000,29.100000,14.600000,22.200000,8.100000,2018.250000,9.250000
max,520764.000000,33452.000000,13665.000000,13162.000000,30.100000,15.300000,23.200000,8.400000,2021.000000,12.000000

In [7]:
year_and_month.style.background_gradient()

In [8]:
year_and_month.style.bar()

In [9]:
def color_all_cells(cell_value):
    highlight_low = 'background-color: SkyBlue;'
    highlight_medium = 'background-color: LightSteelBlue;'
    highlight_big = 'background-color: SteelBlue;'
    default = ''
    
    if type(cell_value) in [float, int]:
        if cell_value <= 253045:
            return highlight_low
        elif cell_value <= 468819.5:
            return highlight_medium
        else:
            return highlight_big
    
    else:
        return default

In [10]:
year_and_month.style.applymap(color_all_cells)