# M3: JSON Web Scraping Assignment

## Introduction

**Instructions:**
Use the requests and pandas libraries to extract and present information from a webpage

**Background:**
This webpage is managed by the Publications Office of the European Union and contains historical catalogue statistics. The dataset below includes information regarding the total number of datasets over a period of time.

**Completed By:**
Danni Martin, September 12, 2024

## Obtaining Data

In [1]:
# Import libraries.
import requests
import pandas as pd

In [2]:
## Obtain the JSON data from the official portal for European data.
# URL was obtained by inspecting 'https://data.europa.eu/catalogue-statistics/evolution/?locale=en'.
search_url = 'https://data.europa.eu/api/hub/statistics/data/num-datasets'
header = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(search_url, headers=header)

root=response.json()

print(root)

{'name': 'count', 'stats': [{'date': '2019-08-01', 'count': 877625.0}, {'date': '2019-09-01', 'count': 895697.0}, {'date': '2019-10-01', 'count': 926295.0}, {'date': '2019-11-01', 'count': 1009213.0}, {'date': '2019-12-01', 'count': 971281.0}, {'date': '2020-01-01', 'count': 932289.0}, {'date': '2020-02-01', 'count': 946020.0}, {'date': '2020-03-01', 'count': 1055326.0}, {'date': '2020-04-01', 'count': 1050101.0}, {'date': '2020-05-01', 'count': 1082174.0}, {'date': '2020-06-01', 'count': 1075846.0}, {'date': '2020-07-01', 'count': 1091168.0}, {'date': '2020-08-01', 'count': 1085248.0}, {'date': '2020-09-02', 'count': 1049813.0}, {'date': '2020-09-17', 'count': 1091495.0}, {'date': '2020-10-01', 'count': 1161894.0}, {'date': '2020-11-01', 'count': 1205046.0}, {'date': '2020-12-01', 'count': 1184899.0}, {'date': '2021-01-01', 'count': 1114557.0}, {'date': '2021-02-01', 'count': 1269746.0}, {'date': '2021-03-01', 'count': 1127740.0}, {'date': '2021-04-06', 'count': 1146431.0}, {'date': '2021-05-01', 'count': 1124197.0}, {'date': '2021-06-01', 'count': 1309497.0}, {'date': '2021-06-02', 'count': 1309531.0}, {'date': '2021-07-01', 'count': 1346611.0}, {'date': '2021-08-01', 'count': 1378140.0}, {'date': '2021-09-01', 'count': 1393493.0}, {'date': '2021-09-21', 'count': 1253575.0}, {'date': '2021-10-01', 'count': 1248832.0}, {'date': '2021-11-01', 'count': 1099503.0}, {'date': '2021-12-01', 'count': 1156937.0}, {'date': '2022-01-01', 'count': 1306839.0}, {'date': '2022-02-01', 'count': 1297866.0}, {'date': '2022-03-01', 'count': 1397588.0}, {'date': '2022-04-01', 'count': 1438808.0}, {'date': '2022-05-01', 'count': 1447514.0}, {'date': '2022-06-01', 'count': 1465771.0}, {'date': '2022-07-01', 'count': 1496754.0}, {'date': '2022-08-01', 'count': 1426864.0}, {'date': '2022-09-01', 'count': 1439816.0}, {'date': '2022-09-07', 'count': 1415834.0}, {'date': '2022-10-01', 'count': 1444824.0}, {'date': '2022-11-01', 'count': 1530764.0}, {'date': '2022-11-07', 'count': 1528549.0}, {'date': '2022-11-08', 'count': 1527490.0}, {'date': '2022-11-14', 'count': 1529306.0}, {'date': '2022-12-01', 'count': 1553902.0}, {'date': '2023-01-01', 'count': 1503404.0}, {'date': '2023-02-01', 'count': 1581648.0}, {'date': '2023-03-01', 'count': 1620007.0}, {'date': '2023-04-01', 'count': 1607267.0}, {'date': '2023-05-01', 'count': 1618996.0}, {'date': '2023-06-01', 'count': 1598660.0}, {'date': '2023-08-01', 'count': 1531285.0}, {'date': '2023-09-01', 'count': 1544800.0}, {'date': '2023-10-01', 'count': 1571156.0}, {'date': '2023-11-01', 'count': 1585007.0}, {'date': '2023-12-01', 'count': 1615595.0}, {'date': '2024-01-01', 'count': 1645657.0}, {'date': '2024-02-01', 'count': 1670976.0}, {'date': '2024-03-01', 'count': 1684156.0}, {'date': '2024-04-01', 'count': 1702660.0}, {'date': '2024-05-01', 'count': 1722624.0}, {'date': '2024-06-01', 'count': 1745683.0}, {'date': '2024-07-01', 'count': 1752765.0}, {'date': '2024-08-01', 'count': 1783602.0}]}

## Programming

In [3]:
## Create the code in Python to obtain the data, and get it into a table using pandas.
df = pd.DataFrame(root['stats'])

## Presenting

In [4]:
## Print the head and tail of the table.
# Print head.
df.head()

         date      count
0  2019-08-01   877625.0
1  2019-09-01   895697.0
2  2019-10-01   926295.0
3  2019-11-01  1009213.0
4  2019-12-01   971281.0

In [5]:
# Print tail.
df.tail()

          date      count
62  2024-04-01  1702660.0
63  2024-05-01  1722624.0
64  2024-06-01  1745683.0
65  2024-07-01  1752765.0
66  2024-08-01  1783602.0

In [6]:
## Indicate how many records are in the table, counting the length of the file. Print your name.
# Print length of file.
print('Length of File:', len(df))

# Print name.
print('Name: Danni Martin')

Length of File: 67
Name: Danni Martin