# M3: HTML Web Scraping Assignment

## Introduction

**Instructions:**
Use the requests, BeautifulSoup, and pandas libraries to extract information from a webpage.

**Background:**
This webpage is hosted by the University of California, Irvine and contains a list of schools and translation data. This webpage facilitates translations from international schools' GPA scales to the US 4.0 scale.

**Completed By:**
Danni Martin, September 12th, 2024.

In [18]:
## Print name.
print('Danni Martin')

Danni Martin

## Obtaining Data

In [19]:
# Import libraries.
import requests  # Internet information requests
from bs4 import BeautifulSoup  # Parsing HTML
import pandas as pd # Enables code to create a sublist using a dataframe

In [20]:
## Write the code in Python to obtain and parse the data with requests and BeautifulSoup
# Send GET request to specified URL.
url = 'https://gpa.eng.uci.edu/'
html_doc = requests.get(url).content

# Parse HTML file.
parsed_html = BeautifulSoup(html_doc)

# Print parsed HTML.
print(parsed_html)

# Assign rows to table.
table = parsed_html.find_all('tr')

# Print table.
print(table)

<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ --><!--[if lt IE 7]> <html class="no-js ie6 ie" xmlns="http://www.w3.org/1999/xhtml" lang="en" dir="ltr"> <![endif]--><!--[if IE 7]>    <html class="no-js ie7 ie" xmlns="http://www.w3.org/1999/xhtml" lang="en" dir="ltr"> <![endif]--><!--[if IE 8]>    <html class="no-js ie8 ie" xmlns="http://www.w3.org/1999/xhtml" lang="en" dir="ltr"> <![endif]--><!--[if IE 9]>    <html class="no-js ie9 ie" xmlns="http://www.w3.org/1999/xhtml" lang="en" dir="ltr"> <![endif]--><!--[if gt IE 9]><!--><html class="no-js" dir="ltr" lang="en" xmlns="http://www.w3.org/1999/xhtml"> <!--<![endif]-->
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="Drupal 7 (http://drupal.org)" name="Generator"/>
<link href="https://gpa.eng.uci.edu/misc/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon"/>
<title>International GPA | International GPA calculator</title>
<link href="https://gpa.eng.uci.edu/sites/default/files/css/css_xE-rWrJf-fncB6ztZfd2huxqgxu4WO-qwma6Xer30m4.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://gpa.eng.uci.edu/sites/default/files/css/css_teRU3nZZdypoIqswbYzUHzwE5iiYErQEBJLLWdM0Y-A.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://gpa.eng.uci.edu/sites/default/files/css/css_jENQOQqZCRFGZK__DTefxYiXR2RUf03k1ugj3_Vg7vk.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://gpa.eng.uci.edu/sites/default/files/css/css_e5JDpOAzQf6Y27WMc64ZU4mk6sNTRh1RL-83wq9XkQY.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://gpa.eng.uci.edu/sites/default/files/css/css_EzvMygEGAnH2SnfZY2CuYiJ8qgZ4RrmaEpy53eCNrMo.css" media="all" rel="stylesheet" type="text/css"/>
<script src="https://gpa.eng.uci.edu/sites/default/files/js/js_YD9ro0PAqY25gGWrTki6TjRUG8TdokmmxjfqpNNfzVU.js" type="text/javascript"></script>
<script src="https://gpa.eng.uci.edu/sites/default/files/js/js_1kmqaL-ZHNpUzE1MbRYi4nlI_AXpH1XP9HPtnQDYngw.js" type="text/javascript"></script>
<script src="https://gpa.eng.uci.edu/sites/default/files/js/js_Z1dT-WFk4FS9cVOf3uo8Yj8YbGKGeGhYhV2uAsLRJm8.js" type="text/javascript"></script>
<script src="https://gpa.eng.uci.edu/sites/default/files/js/js_RzUQypn55D1If6EWZCRgpUOBjodWCQwvtf3E4OrrXS0.js" type="text/javascript"></script>
<script src="https://gpa.eng.uci.edu/sites/default/files/js/js_1Wr66s3cFHFv0wNuEi7jeUl6NrMxIUlMwJQ05FSKwDo.js" type="text/javascript"></script>
<script type="text/javascript">
<!--//--><![CDATA[//><!--
jQuery.extend(Drupal.settings, {"basePath":"\/","pathPrefix":"","setHasJsCookie":0,"ajaxPageState":{"theme":"uci_marina","theme_token":"72QNU51xVKsvhXUrIM5ZvgQ_vJczT7oBO7rPyq5m7g4","js":{"misc\/jquery.js":1,"misc\/jquery-extend-3.4.0.js":1,"misc\/jquery-html-prefilter-3.5.0-backport.js":1,"misc\/jquery.once.js":1,"misc\/drupal.js":1,"misc\/jquery.cookie.js":1,"misc\/jquery.form.js":1,"misc\/form-single-submit.js":1,"misc\/ajax.js":1,"sites\/all\/modules\/custom\/gpa\/gpa.js":1,"sites\/all\/modules\/contrib\/views\/js\/base.js":1,"misc\/progress.js":1,"sites\/all\/modules\/contrib\/views\/js\/ajax_view.js":1,"sites\/all\/modules\/contrib\/ng_lightbox\/js\/ng-lightbox.js":1,"sites\/all\/themes\/fusion\/fusion_core\/js\/script.js":1,"sites\/all\/themes\/fusion\/fusion_core\/skins\/core\/js\/script.js":1},"css":{"modules\/system\/system.base.css":1,"modules\/system\/system.menus.css":1,"modules\/system\/system.messages.css":1,"modules\/system\/system.theme.css":1,"modules\/field\/theme\/field.css":1,"sites\/all\/modules\/custom\/gpa\/gpa.css":1,"modules\/node\/node.css":1,"modules\/user\/user.css":1,"sites\/all\/modules\/contrib\/views\/css\/views.css":1,"sites\/all\/modules\/contrib\/ctools\/css\/ctools.css":1,"sites\/all\/themes\/fusion\/fusion_core\/css\/fusion-style.css":1,"sites\/all\/themes\/fusion\/fusion_core\/css\/fusion-typography.css":1,"sites\/all\/themes\/fusion\/fusion_core\/skins\/core\/fusion-core-skins.css":1,"sites\/all\/themes\/fusion_marina\/css\/fusion-marina-style.css":1,"sites\/all\/themes\/fusion_marina\/skins\/fusion_marina_default\/fusion-marina-default.css":1,"sites\/all\/themes\/fusion\/fusion_core\/css\/grid16-fluid.css":1,"sites\/all\/themes\/uci_marina\/css\/local.css":1}},"urlIsAjaxTrusted":{"\/gpa":true,"\/views\/ajax":true},"views":{"ajax_path":"\/views\/ajax","ajaxViews":{"views_dom_id:c134b7a4362a19364a7b9c3c94be0f3f":{"view_name":"gpa","view_display_id":"page","view_args":"","view_path":"gpa","view_base_path":"gpa","view_dom_id":"c134b7a4362a19364a7b9c3c94be0f3f","pager_element":0}}}});
//--><!]]>
</script>
</head>
<body class="html front not-logged-in no-sidebars page-gpa font-size-13 grid-type-fluid grid-width-16 fluid-95 sidebars-split" id="pid-gpa">
<div id="skip-link">
<a href="#main-content-area">Skip to main content area</a>
</div>
<div class="page" id="page">
<div class="page-inner" id="page-inner">
<!-- header-group region: width = grid_width -->
<div class="header-group-wrapper full-width clearfix" id="header-group-wrapper">
<div class="header-group region grid16-16" id="header-group">
<div class="header-group-inner inner clearfix" id="header-group-inner">
<div class="header-site-info clearfix" id="header-site-info">
<div class="header-site-info-inner gutter" id="header-site-info-inner">
<div id="logo">
<a href="/" title="Home"><img alt="Home" src="https://gpa.eng.uci.edu/sites/all/themes/uci_marina/logo.png"/></a>
</div>
</div><!-- /header-site-info-inner -->
</div><!-- /header-site-info -->
</div><!-- /header-group-inner -->
</div><!-- /header-group -->
</div><!-- /header-group-wrapper -->
<!-- main-menu region -->
<div class="main-menu-wrapper full-width clearfix" id="main-menu-wrapper">
<div class="region region-main-menu main-menu grid16-16" id="main-menu">
<div class="main-menu-inner inner" id="main-menu-inner">
<div class="block block-system block-menu first last odd" id="block-system-main-menu">
<div class="inner clearfix gutter">
<div class="inner-wrapper">
<div class="inner-inner">
<div class="block-icon pngfix"></div>
<h2 class="title block-title">Main menu</h2>
<div class="content clearfix">
<ul class="menu"><li class="first last leaf"><a class="active" href="/">Home</a></li>
</ul> </div>
</div><!-- /inner-inner -->
</div><!-- /inner-wrapper -->
</div><!-- /block-inner -->
</div><!-- /block -->
</div><!-- /main-menu-inner -->
</div><!-- /main-menu -->
</div><!-- /main-menu-wrapper -->
<div class="preface-top-outer"></div>
<!-- main region: width = grid_width -->
<div class="main-wrapper full-width clearfix" id="main-wrapper">
<div class="main region grid16-16" id="main">
<div class="main-inner inner clearfix" id="main-inner">
<!-- main group: width = grid_width - sidebar_first_width -->
<div class="main-group region nested grid16-16" id="main-group">
<div class="main-group-inner inner" id="main-group-inner">
<div class="main-content region nested" id="main-content">
<div class="main-content-inner inner" id="main-content-inner">
<!-- content group: width = grid_width - sidebar_first_width - sidebar_second_width -->
<div class="content-group region nested" id="content-group" style="width:100%">
<div class="content-group-inner inner" id="content-group-inner">
<div class="content-region region nested" id="content-region">
<div class="content-region-inner inner" id="content-region-inner">
<a id="main-content-area"></a>
<h1 class="title gutter">International GPA</h1>
<!-- content region -->
<div class="region region-content content nested grid16-16" id="content" style="width:100%">
<div class="content-inner inner" id="content-inner">
<div class="block block-system first last odd" id="block-system-main">
<div class="inner clearfix gutter">
<div class="inner-wrapper">
<div class="inner-inner">
<div class="content clearfix">
<div class="view view-gpa view-id-gpa view-display-id-page view-dom-id-c134b7a4362a19364a7b9c3c94be0f3f">
<div class="view-filters">
<form accept-charset="UTF-8" action="/gpa" id="views-exposed-form-gpa-page" method="get"><div><div class="views-exposed-form">
<div class="views-exposed-widgets clearfix">
<div class="views-exposed-widget views-widget-filter-title" id="edit-title-wrapper">
<label for="edit-title">
            School name          </label>
<div class="views-widget">
<div class="form-item form-type-textfield form-item-title">
<input class="form-text" id="edit-title" maxlength="128" name="title" size="30" type="text" value=""/>
</div>
</div>
</div>
<div class="views-exposed-widget views-widget-filter-field_country_value" id="edit-field-country-value-wrapper">
<label for="edit-field-country-value">
            Country          </label>
<div class="views-widget">
<div class="form-item form-type-textfield form-item-field-country-value">
<input class="form-text" id="edit-field-country-value" maxlength="128" name="field_country_value" size="30" type="text" value=""/>
</div>
</div>
</div>
<div class="views-exposed-widget views-widget-filter-field_school_code_value" id="edit-field-school-code-value-wrapper">
<label for="edit-field-school-code-value">
            School code          </label>
<div class="views-widget">
<div class="form-item form-type-textfield form-item-field-school-code-value">
<input class="form-text" id="edit-field-school-code-value" maxlength="128" name="field_school_code_value" size="30" type="text" value=""/>
</div>
</div>
</div>
<div class="views-exposed-widget views-submit-button">
<input class="form-submit" id="edit-submit-gpa" type="submit" value="Search"/> </div>
<div class="views-exposed-widget views-reset-button">
<input class="form-submit" id="edit-reset" name="op" type="submit" value="Reset"/> </div>
</div>
</div>
</div></form> </div>
<div class="view-content">
<table class="views-table cols-7">
<thead>
<tr>
<th class="views-field views-field-title" scope="col">
<a class="active" href="/gpa?order=title&amp;sort=asc" title="sort by School name">School name</a> </th>
<th class="views-field views-field-field-location" scope="col">
<a class="active" href="/gpa?order=field_location&amp;sort=asc" title="sort by Location">Location</a> </th>
<th class="views-field views-field-field-country" scope="col">
<a class="active" href="/gpa?order=field_country&amp;sort=asc" title="sort by Country">Country</a> </th>
<th class="views-field views-field-field-school-code" scope="col">
<a class="active" href="/gpa?order=field_school_code&amp;sort=asc" title="sort by School code">School code</a> </th>
<th class="views-field views-field-field-intl-gpa" scope="col">
<a class="active" href="/gpa?order=field_intl_gpa&amp;sort=asc" title="sort by Intl GPA">Intl GPA</a> </th>
<th class="views-field views-field-field-us-gpa" scope="col">
<a class="active" href="/gpa?order=field_us_gpa&amp;sort=asc" title="sort by US GPA">US GPA</a> </th>
<th class="views-field views-field-nid" scope="col">
<a class="active" href="/gpa?order=nid&amp;sort=asc" title="sort by Action">Action</a> </th>
</tr>
</thead>
<tbody>
<tr class="odd views-row-first">
<td class="views-field views-field-title">
<a href="/node/380">DEFAULT Argentina</a> </td>
<td class="views-field views-field-field-location">
</td>
<td class="views-field views-field-field-country">
            Argentina          </td>
<td class="views-field views-field-field-school-code">
</td>
<td class="views-field views-field-field-intl-gpa">
            10/9/7.5/6          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.6/3.0/2.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/380">calc</a> </td>
</tr>
<tr class="even">
<td class="views-field views-field-title">
<a href="/node/4">Australian National University</a> </td>
<td class="views-field views-field-field-location">
            Canberra          </td>
<td class="views-field views-field-field-country">
            Australia          </td>
<td class="views-field views-field-field-school-code">
            7211413          </td>
<td class="views-field views-field-field-intl-gpa">
            100/80/70/60          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.6/3.0/2.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/4">calc</a> </td>
</tr>
<tr class="odd">
<td class="views-field views-field-title">
<a href="/node/391">Monash University</a> </td>
<td class="views-field views-field-field-location">
            Melbourne, Victoria          </td>
<td class="views-field views-field-field-country">
            Australia          </td>
<td class="views-field views-field-field-school-code">
            S135987          </td>
<td class="views-field views-field-field-intl-gpa">
            100/80/70/60          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.6/3.0/2.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/391">calc</a> </td>
</tr>
<tr class="even">
<td class="views-field views-field-title">
<a href="/node/395">The University of New South Wales</a> </td>
<td class="views-field views-field-field-location">
            Sydney          </td>
<td class="views-field views-field-field-country">
            Australia          </td>
<td class="views-field views-field-field-school-code">
            S131001          </td>
<td class="views-field views-field-field-intl-gpa">
            100/85/75/65          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.6/3.0/2.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/395">calc</a> </td>
</tr>
<tr class="odd">
<td class="views-field views-field-title">
<a href="/node/428">The University of Queensland</a> </td>
<td class="views-field views-field-field-location">
            Queensland          </td>
<td class="views-field views-field-field-country">
            Australia          </td>
<td class="views-field views-field-field-school-code">
</td>
<td class="views-field views-field-field-intl-gpa">
            7/6/5/4/3          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.0/2.0/1.0/0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/428">calc</a> </td>
</tr>
<tr class="even">
<td class="views-field views-field-title">
<a href="/node/330">University of Melbourne</a> </td>
<td class="views-field views-field-field-location">
            Melbourne          </td>
<td class="views-field views-field-field-country">
            Australia          </td>
<td class="views-field views-field-field-school-code">
            7221002          </td>
<td class="views-field views-field-field-intl-gpa">
            100/80/75/70/65          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.6/3.0/2.0/1.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/330">calc</a> </td>
</tr>
<tr class="odd">
<td class="views-field views-field-title">
<a href="/node/398">University Of Sydney</a> </td>
<td class="views-field views-field-field-location">
            Sydney          </td>
<td class="views-field views-field-field-country">
            Australia          </td>
<td class="views-field views-field-field-school-code">
</td>
<td class="views-field views-field-field-intl-gpa">
            100/85/75/65          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.6/3.0/2.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/398">calc</a> </td>
</tr>
<tr class="even">
<td class="views-field views-field-title">
<a href="/node/345">Johannes Kepler University Linz</a> </td>
<td class="views-field views-field-field-location">
            Linz          </td>
<td class="views-field views-field-field-country">
            Austria          </td>
<td class="views-field views-field-field-school-code">
</td>
<td class="views-field views-field-field-intl-gpa">
            1/2/3/4          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.0/2.0/1.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/345">calc</a> </td>
</tr>
<tr class="odd">
<td class="views-field views-field-title">
<a href="/node/5">Qafqaz University</a> </td>
<td class="views-field views-field-field-location">
</td>
<td class="views-field views-field-field-country">
            Azerbaijan          </td>
<td class="views-field views-field-field-school-code">
</td>
<td class="views-field views-field-field-intl-gpa">
            100/85/65/50          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.6/3.0/2.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/5">calc</a> </td>
</tr>
<tr class="even">
<td class="views-field views-field-title">
<a href="/node/6">Bangladesh University of Engineering and Technology, Dhaka</a> </td>
<td class="views-field views-field-field-location">
</td>
<td class="views-field views-field-field-country">
            Bangladesh          </td>
<td class="views-field views-field-field-school-code">
            7211821          </td>
<td class="views-field views-field-field-intl-gpa">
            4.0/3.7/3.3/3.0/2.7/2.3/2.0          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.7/3.3/3.0/2.7/2.3/2.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/6">calc</a> </td>
</tr>
<tr class="odd">
<td class="views-field views-field-title">
<a href="/node/396">DEFAULT Bangladesh</a> </td>
<td class="views-field views-field-field-location">
</td>
<td class="views-field views-field-field-country">
            Bangladesh          </td>
<td class="views-field views-field-field-school-code">
</td>
<td class="views-field views-field-field-intl-gpa">
            100/60/45/33          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.6/3.0/2.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/396">calc</a> </td>
</tr>
<tr class="even">
<td class="views-field views-field-title">
<a href="/node/7">Rajshahi University of Engineering and Technology - 4.0 Scale</a> </td>
<td class="views-field views-field-field-location">
</td>
<td class="views-field views-field-field-country">
            Bangladesh          </td>
<td class="views-field views-field-field-school-code">
</td>
<td class="views-field views-field-field-intl-gpa">
            4.0/3.7/3.3/3.0/2.7/2.3/2.0          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.7/3.3/3.0/2.7/2.3/2.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/7">calc</a> </td>
</tr>
<tr class="odd">
<td class="views-field views-field-title">
<a href="/node/8">Rajshahi University of Engineering and Technology - Percentages</a> </td>
<td class="views-field views-field-field-location">
</td>
<td class="views-field views-field-field-country">
            Bangladesh          </td>
<td class="views-field views-field-field-school-code">
</td>
<td class="views-field views-field-field-intl-gpa">
            100/70/65/60/55/50/45          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.6/3.3/3.0/2.7/2.3/2.0          </td>
<td class="views-field views-field-nid">
<a class="ng-lightbox" href="/node/8">calc</a> </td>
</tr>
<tr class="even">
<td class="views-field views-field-title">
<a href="/node/474">DEFAULT Belgium - 100-point scale</a> </td>
<td class="views-field views-field-field-location">
</td>
<td class="views-field views-field-field-country">
            Belgium          </td>
<td class="views-field views-field-field-school-code">
</td>
<td class="views-field views-field-field-intl-gpa">
            100/90/80/70/60          </td>
<td class="views-field views-field-field-us-gpa">
            4.0/3.7/3.3/3.0/2.0          </td>

## Programming

In [21]:
## Create a list of sublists (the values for each row in the table).
# Extract <th> from first row of table and remove whitespace. Results assigned to 'headings'.
headings = [th.text.strip() for th in table[0].find_all('th')]

# Extract <td> from table (excluding header row) and remove whitespace.
# Create sublist for each row using list comprehension. Final results assigned to 'rows'.
rows = [[td.text.strip() for td in row.find_all('td')] for row in table[1:]]

# Print lists.
print(headings)
print(rows)

['School name', 'Location', 'Country', 'School code', 'Intl GPA', 'US GPA', 'Action']

In [22]:
## Create a data frame containing the values of the list in a table using pandas.
df = pd.DataFrame(rows, columns=headings)

## Presenting

In [23]:
## Print the head and tail of the table.
# Print head.
df.head()

,School name,Location,Country,School code,Intl GPA,US GPA,Action
0,DEFAULT Argentina,,Argentina,,10/9/7.5/6,4.0/3.6/3.0/2.0,calc
1,Australian National University,Canberra,Australia,7211413,100/80/70/60,4.0/3.6/3.0/2.0,calc
2,Monash University,"Melbourne, Victoria",Australia,S135987,100/80/70/60,4.0/3.6/3.0/2.0,calc
3,The University of New South Wales,Sydney,Australia,S131001,100/85/75/65,4.0/3.6/3.0/2.0,calc
4,The University of Queensland,Queensland,Australia,,7/6/5/4/3,4.0/3.0/2.0/1.0/0,calc

In [24]:
# Print tail.
df.tail()

,School name,Location,Country,School code,Intl GPA,US GPA,Action
465,The University of Sheffield - Undergraduate,Sheffield,United Kingdom,7110427,100/70/60/50,4.0/3.6/3.0/2.0,calc
466,University of Birmingham,,United Kingdom,,100/70/64/60/50/40,4.0/3.7/3.3/3.0/2.0/1.0,calc
467,University of Portsmouth,"Portsmouth, England",United Kingdom,,100/70/60/50,4.0/3.6/3.0/2.0,calc
468,DEFAULT Vietnam,,Vietnam,9807001,10/8/7.5/6/5,4.0/3.6/3.0/2.7/2.0,calc
469,Ho Chi Minh City University of Technology,Saigon,Vietnam,7110219,10/8/7/6/5,4.0/3.6/3.3/3.0/2.0,calc

In [25]:
## Indicate how many records are in the table, counting the file length. Omit the headings in the count.
print('Length of Table:', len(df))

Length of Table: 470